### PR TITLE
Added url to export

### PR DESCRIPTION
**Pull request by AnderssonPeter**
Added code to export Url, note I haven't verified that it is working as I'm somewhat new to go.

### CODE REVIEW

**Comment by rsteube** [comment]
It's fine, but using `Long` for url is specific to carapace-bin.
I renamed the members so that they are consistent with cobra.

**Review by rsteube — APPROVED** [review]

**Comment by AnderssonPeter** [comment]
@rsteube Thanks for the quick merge, any chance you could release a new version with the changes so I can export new files?
Thanks for all the help :)

**Comment by rsteube** [comment]
Just add the following to `go.mod` of carapace-bin and build it:
```go
replace github.com/rsteube/carapace => github.com/rsteube/carapace master
```

**Comment by AnderssonPeter** [comment]
@rsteube I added the replace line but then got a error so I ran `go mod download github.com/rsteube/carapace` this replaced your line with `replace github.com/rsteube/carapace => github.com/rsteube/carapace v0.12.3-0.20220118114642-3cd32d21f3eb` (Seems correct as the latest commit hash starts with 3cd)

Then I followed your instructions in 
`README.md`
`cd cmd/carapace && go generate ./... && go build -ldflags="-s -w" -tags release`
 but that yields the following error:
`main.go:3:8: //go:build comment without // +build comment`

I'm guessing that `go generate ./...` is supposed to fix the comment error but nothing happens..

**Comment by rsteube** [comment]
This sounds more like an old Go version on your device.

**Comment by AnderssonPeter** [comment]
I'm using a docker desktop dev environment, and it seems to come with 1.16.7, when trying to update it to 1.17.6 it exploded in my face 💥💥💥

**Comment by AnderssonPeter** [comment]
That worked thanks :)

**Pull request merged**
