### PR TITLE
API: Add a CacheF() function to control completion cache refresh

### PR DESCRIPTION
**Pull request by maxlandon**

### CODE REVIEW

**Comment by rsteube** [comment]
Need to give this some thinking when i got the time. I feel like this should already be doable with the timeout (e.g. zero duration) and key arguments.
If anything i'd probably opt for a custom error returned by the key furnction :thinking: .

**Comment by maxlandon** [comment]
You might very well be right, and its probable that I've come to open this PR just because I over complicated my own use of the cache in some instances.

**Comment by maxlandon** [comment]
Two other things:
1 - I saw you started leveraging lexers for command-line consumption, great idea, curious to see what wonders you'll do with this.
2 - I tried to attack this infamous cobra global comp map, here: https://github.com/spf13/cobra/pull/2012#issuecomment-1669585151, if you have anything you'd like to contribute in order to pull this chard out of everyone's foot, that will be my joy !

**Comment by rsteube** [comment]
Yes, zero timeout duration seems to do the trick.
Writing a lexer is actually something i wanted to avoid, but it is needed for [Split](https://rsteube.github.io/carapace/carapace/action/split.html).

**Pull request closed without merging**
