### PR TITLE
ZSH grouped/aliased completions

### PR DESCRIPTION
**Pull request by maxlandon**
arguments
options

## Features and enhancements

This PR enhances ZSH completion with multiple new features.
Most of them rely on using the `_describe` helper rather than `compadd`.

### ZSH specific
- Completions can now be grouped together under a description, with `action.Group(name)`.
- Completions being aliases of each other (-f/--files, or command aliases) are now displayed
  together in completion listings.
- Zstyle coloring has been adapted to still work despite those changes.
- Padding dynamically and smartly computed, depending on the current "profile" of the completions.
- Messages are now displayed through the `_message` ZSH helper, which now allows us to pass messages
  of arbitrary length, and with arbitrary color formatting *within them* (therefore, and provided
  left at the discretion of the library user).
- Better suffix autoremoval, with patterns passed to the `compadd` calls, for instance autoremoval of a space suffix when another space is entered, or when a non-nil character is typed (with NoOptDefVal flags). Also used in list completions.

### Other/all shells
- Flags that are marked repeatable (slices and maps) now use a default multiparts completer with a comma list item separator.

## Major changes to the code

- The ZSH snippet has been modified so as to loop over an arbitrary number of groups, and generate
  their completions accordingly. It does also parses a header for each group, containing its tag
  and group description.
- The ZSH Go code has been rewritten (entirely), in order to account for all the changes and cases
  to be considered. The code is heavily commented, so as to ease understanding the logic involved,
  the constraints faced, etc. I *pretend* this code to be shielded from *most* edge cases. See below.
- The action used to generate command completions has been modified to structure them by groups, if
  there are any (takes advantage of this new cobra v.1.6.0 feature).
- The `ActionMessage()` has been rewritten, because I had to find a way to pass messages to the final
  `ActionRawValues()` functions, while preserving compatibility with other shells. See below as well.
  A corresponding function call has been added in all shells Go code, except for ZSH which does different.
- The `common.RawValue` type now has a `Tag` and a `Group` field. This is so that people can still generate
  as many actions from a base one (shoutouts to how you devised this library). See [this file](https://github.com/reeflective/flags/blob/validator/examples/args/positionals.go)
  for an example where I make use of these groups (as well as of the old and new carapace features)
- `Merge()` has been slightly modified to preserve the order in which completions (therefore groups)
  were added.
- ZSH sanitizers have been *very slightly* modified, in order to acomodate for the changes, and placed
  into a file of their own.

### CODE REVIEW

**Comment by rsteube** [comment]
Thanks for giving this a try!
Completion groups and tags are something very specific to zsh only though and add complexity with limited benefits.
Give me some time to think about it but unfortunately i must say i am against adding it as a feature (at least for the moment).

**Comment by maxlandon** [comment]
As you want ! 

Note though:
- Writing this I realized how well this library is designed because it enables one to enhance/modify behavior on one shell, without modifying the behavior on others: as long as no one changes the `ActionRawValues()` signature, this is guaranteed.
- In turn, this made me think that sometimes an enhancement made for one shell can then prop up other shells to host such similar enhancement.
- Most things that were not working at the end of the first series of commits got fixed. I need to test the whole thing manually for all shells, and will do with the help you gave in the refactoring PR.
- I merged back  the last commits you made on master, will continue to do so for some time.
 
 Among other things added in the last 5 commits:
 - Flags are checked if repeatable, and if yes, support comma-separated list completions.
 - Better suffix autoremoval behavior for ZSH (opt args, shorthand series, etc)
 
 I edited the above initial description to reflect changes, fixes, todos, etc.

**Comment by rsteube** [comment]
>  Writing this I realized how well this library is designed because it enables one to enhance/modify behavior on one shell, without modifying the behavior on others: as long as no one changes the ActionRawValues() signature, this is guaranteed.

It's less designed but went though lots of (painful) iterations while creating completers in carapace-bin and realizing what's actually needed and how it can be done.

> In turn, this made me think that sometimes an enhancement made for one shell can then prop up other shells to host such similar enhancement.

I have the same hope for things like color to be adopted by other shells,
but it's not `zsh` setting the bar in carapace but `elvish` (https://elv.sh/).
I'm rather opposed to most the `zsh` specifics which also makes this PR also a bit hard because it touches a lot of topics i have explicitly decided against.

So i currently have to rethink if those decisions are still valid.

**Comment by maxlandon** [comment]
### On your last comment
I fully get how many tries and failures must been needed to arrive to the point where this library
is. This is why it's a very impressive work, and the tradeoffs you made in designing will not hamper
on using carapace and further developing it (this is at least a happy prediction I'm making here)

Consequently, and I only realize it now, suddenly my PR appears quite big (too big), and I shall probably
refactor it into smaller ones. If only for more easily proposing you things to cherry pick.

More broadly, and anyone having been using a terminal long enough will also agree, it is indeed 
very important not to rush on features or into mistakingly pushing personal preferences as defaults
(which in my short experience writing CLI libraries, is a trap one can easily fall in -as I did-)

Nonetheless I saw that you used some of the ideas outlined above, for instance the suffix matchers 
principle. Really cool !


### About elvish
So that was the opportunity for me to check this shell again, which personally I've been reluctant to use
because of its completion system default behavior. And only for this, like many other people, judging at the
open/close issues on the subject.

This shell project is probably another example of how hard it is to implement a versatile but sane completion/UX
system, preserving the smart ideas of other shells while not carrying on their bad choices. 

Concerning our matter, some people have -or currently- are, proposing/thinking of- how to implement various
completion system features, some of which being those tag/groups principles. Linking those discussion below.
Obviously those are not planned short-term, and they will not make their way into the elvish shell before long.

Links:
[Issue for adding completion types](https://github.com/elves/elvish/issues/914)
[Redesign ideas](https://github.com/elves/elvish/issues/581)
[A good example of personal preferences turning into a burden](https://github.com/elves/elvish/issues/322)

### Work to come on this PR

- Similarly to #583, I will merge back the changes you've pushed to master, to thin this PR even more.
- I also noticed the enhancements you've pushed, like args lists completions. This is part of the stuff
  I need to trim out from this PR, because it's not needed here anymore.
- Again, the ultimate goal here being to keep it on sync with master, and progressively thin it up until
  there is only ZSH-related code, which you'll be free to integrate or not. The point here being to simplify
  anything that can be and leaving as many options as possible.
- Also noted in #583, I'll try to split this PR into smaller ones, if there is anything still relevant here.

Finally, and because one must give time to time, I'll keep commenting and pushing code/ideas here and there,
not necessarily related to ZSH specifics. There will be PRs opened in the coming weeks, in order to discuss
every problem/feature separately.

**Comment by rsteube** [comment]
@maxlandon First of all awesome job getting all of this working!!!
The zsh stuff was a massive pain in the past so this is a great help.

Sorry for taking my time on this but there are a lot of fragile parts and things to consider.
It was also a bit overwhelming in the beginning.
I've got a decent overview of the changes now and am merging things step by step.
This way i can test things separately and fully understand what is going on.


- Tags
Support is added (though not yet the zsh integration). 
I think how these are grouped should be up to the user/shell.
As far as i understand this should provide enough information for that.
It is also implicitly set for command groups.

- SuffixRemovable
Don't (yet) think that this should be added explicitly to RawValue.
There is potential though that the `Nospace` (SuffixMatcher) might already provide sufficient information for this.
I'm just worried there might be some cases where the removal might be unwanted.

- Hint
Added as `Usage` (as it's called this in cobra) with implicit flag and command usage set.

- ActionMessage
Added custom struct so that more than one message is supported (e.g. when merging different Actions with Batch).
Also provides the current integration as RawValue for shells without support for messages.

- _describe
Seems to work now (caused me massive pains in the past). Good job finding out how to do the zstyle for that (duh!).
Really like the parsing with `read`. Didn't know before how that works exactly, so thanks for showing me.


Btw. imo the line comments reduce the readability/maintenance quite a bit, i am much more in favor of the struct/function extractions you did.
Currently feel that the shell specifics and how they are approached is better added to the developer documentation (which is still a bit scarce).

**Comment by maxlandon** [comment]
Hello Rob !
Well first of all: I've noticed with great pleasure that you integrated the changes, and ... you did it even better than what I could have done :) ! Really glad about this !

Especially:
- SuffixMatcher: what a GREAT way of treating this !
- common.Meta and messages: same, really really really great.

So, I guess this PR is quite done, as all of the proposed features have been implemented and greater.
Feel free to close it if you feel the need.

Additionally, answering something I saw in your code: https://github.com/rsteube/carapace/blob/4a3ec47030bf75829c2c926f442ff63d4aff02b4/internal/shell/zsh/action.go#L58
The answer is:
When ZSH does not find a comma, it considers the whole string to be used as is, as a display string. When it finds one, it will split the string and use the first part as the candidate part of the display, and the second part as the description. This is so that describe can still use provided display strings even if there are aliased completions.

Again, thanks a huge lot for your consideration and time, I'm really glad of the result and I'm sure I won't be the only one !

**Comment by rsteube** [comment]
Yeah, i kept it open to see if there's more to grab.
Think the essential features are in now though.
Really happy how this turned out as well (even #482 is finally working).

Thanks again for the :rocket:  work on this.

**Pull request closed without merging**
